package info.dummy;
// Generated 6 Aug, 2014 10:59:51 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillMaster generated by hbm2java
 */
@Entity
@Table(name="bill_master"
    ,catalog="lab_db"
)
public class BillMaster  implements java.io.Serializable {


     private Long id;
     private Users users;
     private Doctor doctor;
     private Patient patient;
     private Date billDate;
     private Double discount;
     private Double paid;
     private Double rmpcm;
     private String rmpname;
     private Double amount;
     private Double addvance;
     private Double balance;
     private Set<BillDetails> billDetailses = new HashSet<BillDetails>(0);

    public BillMaster() {
    }

    public BillMaster(Users users, Doctor doctor, Patient patient, Date billDate, Double discount, Double paid, Double rmpcm, String rmpname, Double amount, Double addvance, Double balance, Set<BillDetails> billDetailses) {
       this.users = users;
       this.doctor = doctor;
       this.patient = patient;
       this.billDate = billDate;
       this.discount = discount;
       this.paid = paid;
       this.rmpcm = rmpcm;
       this.rmpname = rmpname;
       this.amount = amount;
       this.addvance = addvance;
       this.balance = balance;
       this.billDetailses = billDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doctor_id")
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patient_id")
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="billDate", length=10)
    public Date getBillDate() {
        return this.billDate;
    }
    
    public void setBillDate(Date billDate) {
        this.billDate = billDate;
    }
    
    @Column(name="discount", precision=22, scale=0)
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    
    @Column(name="paid", precision=22, scale=0)
    public Double getPaid() {
        return this.paid;
    }
    
    public void setPaid(Double paid) {
        this.paid = paid;
    }
    
    @Column(name="rmpcm", precision=22, scale=0)
    public Double getRmpcm() {
        return this.rmpcm;
    }
    
    public void setRmpcm(Double rmpcm) {
        this.rmpcm = rmpcm;
    }
    
    @Column(name="rmpname")
    public String getRmpname() {
        return this.rmpname;
    }
    
    public void setRmpname(String rmpname) {
        this.rmpname = rmpname;
    }
    
    @Column(name="amount", precision=22, scale=0)
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    
    @Column(name="addvance", precision=22, scale=0)
    public Double getAddvance() {
        return this.addvance;
    }
    
    public void setAddvance(Double addvance) {
        this.addvance = addvance;
    }
    
    @Column(name="balance", precision=22, scale=0)
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="billMaster")
    public Set<BillDetails> getBillDetailses() {
        return this.billDetailses;
    }
    
    public void setBillDetailses(Set<BillDetails> billDetailses) {
        this.billDetailses = billDetailses;
    }




}


