package info.dummy;
// Generated 6 Aug, 2014 10:59:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name="patient"
    ,catalog="lab_db"
)
public class Patient  implements java.io.Serializable {


     private String pid;
     private String address;
     private Integer age;
     private String gender;
     private String phoneno;
     private String firstname;
     private String lastname;
     private Set<BillMaster> billMasters = new HashSet<BillMaster>(0);

    public Patient() {
    }

	
    public Patient(String pid, String gender, String firstname) {
        this.pid = pid;
        this.gender = gender;
        this.firstname = firstname;
    }
    public Patient(String pid, String address, Integer age, String gender, String phoneno, String firstname, String lastname, Set<BillMaster> billMasters) {
       this.pid = pid;
       this.address = address;
       this.age = age;
       this.gender = gender;
       this.phoneno = phoneno;
       this.firstname = firstname;
       this.lastname = lastname;
       this.billMasters = billMasters;
    }
   
     @Id 
    
    @Column(name="pid", unique=true, nullable=false)
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    
    @Column(name="address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="age")
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    
    @Column(name="gender", nullable=false)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    
    @Column(name="phoneno")
    public String getPhoneno() {
        return this.phoneno;
    }
    
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }
    
    @Column(name="firstname", nullable=false, length=45)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    
    @Column(name="lastname", length=45)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="patient")
    public Set<BillMaster> getBillMasters() {
        return this.billMasters;
    }
    
    public void setBillMasters(Set<BillMaster> billMasters) {
        this.billMasters = billMasters;
    }




}


