package info.dummy;
// Generated 6 Aug, 2014 10:59:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Testgroup generated by hbm2java
 */
@Entity
@Table(name="testgroup"
    ,catalog="lab_db"
)
public class Testgroup  implements java.io.Serializable {


     private Long groupId;
     private String groupName;
     private Set<Test> tests = new HashSet<Test>(0);

    public Testgroup() {
    }

    public Testgroup(String groupName, Set<Test> tests) {
       this.groupName = groupName;
       this.tests = tests;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="groupId", unique=true, nullable=false)
    public Long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }
    
    @Column(name="groupName")
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="testgroup")
    public Set<Test> getTests() {
        return this.tests;
    }
    
    public void setTests(Set<Test> tests) {
        this.tests = tests;
    }




}


