package info.dummy;
// Generated 6 Aug, 2014 10:59:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name="test"
    ,catalog="lab_db"
)
public class Test  implements java.io.Serializable {


     private Long id;
     private Testgroup testgroup;
     private Double cost;
     private String femaleNormalRange;
     private String maleNormalRange;
     private String name;
     private String scale;
     private String normaltype;
     private String normalresult;

    public Test() {
    }

    public Test(Testgroup testgroup, Double cost, String femaleNormalRange, String maleNormalRange, String name, String scale, String normaltype, String normalresult) {
       this.testgroup = testgroup;
       this.cost = cost;
       this.femaleNormalRange = femaleNormalRange;
       this.maleNormalRange = maleNormalRange;
       this.name = name;
       this.scale = scale;
       this.normaltype = normaltype;
       this.normalresult = normalresult;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="testgroup_id")
    public Testgroup getTestgroup() {
        return this.testgroup;
    }
    
    public void setTestgroup(Testgroup testgroup) {
        this.testgroup = testgroup;
    }
    
    @Column(name="cost", precision=22, scale=0)
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    
    @Column(name="femaleNormalRange")
    public String getFemaleNormalRange() {
        return this.femaleNormalRange;
    }
    
    public void setFemaleNormalRange(String femaleNormalRange) {
        this.femaleNormalRange = femaleNormalRange;
    }
    
    @Column(name="maleNormalRange")
    public String getMaleNormalRange() {
        return this.maleNormalRange;
    }
    
    public void setMaleNormalRange(String maleNormalRange) {
        this.maleNormalRange = maleNormalRange;
    }
    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="scale")
    public String getScale() {
        return this.scale;
    }
    
    public void setScale(String scale) {
        this.scale = scale;
    }
    
    @Column(name="normaltype", length=45)
    public String getNormaltype() {
        return this.normaltype;
    }
    
    public void setNormaltype(String normaltype) {
        this.normaltype = normaltype;
    }
    
    @Column(name="normalresult", length=45)
    public String getNormalresult() {
        return this.normalresult;
    }
    
    public void setNormalresult(String normalresult) {
        this.normalresult = normalresult;
    }
}


